/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.estacionamentoifsul.view;

import br.edu.ifsul.cc.lpoo.estacionamentoifsul.lpoo_sistemaestacionamentoifsul.dao.PersistenciaJPA;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VeiOficial;
import model.Veiculo;

public class TelaVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaVeiculo
     */
    
    private PersistenciaJPA persistencia;
    
    public TelaVeiculo() {
        this.persistencia = new PersistenciaJPA();
        initComponents();
        carregarTabela(persistencia.getVeiculos());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoFiltroPlaca = new javax.swing.JTextField();
        checkOficial = new javax.swing.JCheckBox();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoFiltroPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoFiltroPlacaKeyReleased(evt);
            }
        });

        checkOficial.setText("Oficial");
        checkOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOficialActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Modelo", "Cor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaVeiculos);

        jLabel1.setText("Filtro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFiltroPlaca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover)))
                .addGap(18, 18, 18)
                .addComponent(checkOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkOficial)
                        .addComponent(btnRemover))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo)
                        .addComponent(btnEditar)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoFiltroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaCadastroVeiculo telacadastroveiculo = new TelaCadastroVeiculo();
        telacadastroveiculo.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void campoFiltroPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoFiltroPlacaKeyReleased
        String placa = campoFiltroPlaca.getText().trim();
            boolean apenasOficiais = checkOficial.isSelected();
            List<Veiculo> veiculos = placa.isEmpty()
                    ? persistencia.getVeiculosOficiais(apenasOficiais)
                    : persistencia.getVeiculosPorPlaca(placa);
            carregarTabela(veiculos);
    }//GEN-LAST:event_campoFiltroPlacaKeyReleased

    private void checkOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOficialActionPerformed
        String placa = campoFiltroPlaca.getText().trim();
    boolean apenasOficiais = checkOficial.isSelected();
    List<Veiculo> veiculos = placa.isEmpty()
            ? persistencia.getVeiculosOficiais(apenasOficiais)
            : persistencia.getVeiculosPorPlaca(placa);
    carregarTabela(veiculos);
    }//GEN-LAST:event_checkOficialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
            int row = tabelaVeiculos.getSelectedRow();
    if (row != -1) {
        String placa = tabelaVeiculos.getValueAt(row, 0).toString();
        Veiculo veiculo = persistencia.getVeiculosPorPlaca(placa).get(0); // Corrigido para usar o método de busca adequad        new TelaCadastroVeiculo(this, persistencia, veiculo).setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um veículo para editar!");
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
            int row = tabelaVeiculos.getSelectedRow();
    if (row != -1) {
        String placa = tabelaVeiculos.getValueAt(row, 0).toString();
        Veiculo veiculo = persistencia.getVeiculosPorPlaca(placa).get(0); // Corrigido para buscar o veículo
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja remover o veículo?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                persistencia.remover(veiculo);
                JOptionPane.showMessageDialog(this, "Veículo removido com sucesso!");
                carregarTabela(persistencia.getVeiculos());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao remover veículo: " + ex.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um veículo para remover!");
    }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TelaVeiculo().setVisible(true);
            }
        });
    }
    
    private void carregarTabela(List<Veiculo> listaVeiculos) {
    DefaultTableModel modeloTabela = (DefaultTableModel) tabelaVeiculos.getModel();
    modeloTabela.setRowCount(0); // Limpa a tabela

    for (Veiculo veiculo : listaVeiculos) {
        modeloTabela.addRow(new Object[]{
            veiculo.getPlaca(),
            veiculo.getProprietario() != null ? veiculo.getProprietario().getNome() : "N/A",
            veiculo instanceof VeiOficial ? "Sim" : "Não"
        });
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField campoFiltroPlaca;
    private javax.swing.JCheckBox checkOficial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaVeiculos;
    // End of variables declaration//GEN-END:variables
}